name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update apt
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get update -qq -o Acquire::Retries=3

      - name: Install platform dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run:
          sudo apt-get install --fix-missing -qq -o Acquire::Retries=3
                gtk-doc-tools
                gobject-introspection
                python3-pip
                python3-setuptools
                python3-wheel
                libfftw3-dev
                libexif-dev
                libjpeg-turbo8-dev
                libpng-dev
                libwebp-dev
                libtiff5-dev
                libde265-0
                libheif-dev
                libexpat1-dev
                libcfitsio-dev
                libgsl-dev
                libmatio-dev
                libnifti-dev
                liborc-0.4-dev
                liblcms2-dev
                libpoppler-glib-dev
                librsvg2-dev
                libgif-dev
                libopenexr-dev
                libpango1.0-dev
                libgsf-1-dev
                libopenslide-dev
                libffi-dev

      - name: Configure libvips
        run: CFLAGS=-Wall CXXFLAGS=-Wall ./autogen.sh
            --disable-dependency-tracking
            --disable-deprecated

      - name: Build libvips
        run: make V=0

      - name: Check libvips
        run: make V=0 check

      - name: Install libvips
        run: sudo make V=0 install

      - name: Install pyvips
        run: pip3 install pyvips pytest

      - name: Run test suite
        run: pytest
